### ISSUE TITLE
nice tool, but compile fail with latest build tools

### ISSUE THREAD

**Issue by skydig** [zhenyuanlau/rshell#1]
error[E0560]: struct `nix::libc::sockaddr_in` has no field named `sin_len`
  --> src/macros/mod.rs:7:13
   |
7  |             sin_len: std::mem::size_of::<libc::sockaddr_in>() as u8,
   |             ^^^^^^^ `nix::libc::sockaddr_in` does not have this field
   |
  ::: src/client.rs:19:24
   |
19 |         let servaddr = sockaddr!([127, 0, 0, 1], 8000);
   |                        ------------------------------- in this macro invocation
   |
   = note: available fields are: `sin_family`, `sin_port`, `sin_addr`, `sin_zero`

error[E0560]: struct `nix::libc::sockaddr_in` has no field named `sin_len`
  --> src/macros/mod.rs:7:13
   |
7  |             sin_len: std::mem::size_of::<libc::sockaddr_in>() as u8,
   |             ^^^^^^^ `nix::libc::sockaddr_in` does not have this field
   |
  ::: src/server.rs:69:24
   |
69 |         let servaddr = sockaddr!([127, 0, 0, 1], 8000);
   |                        ------------------------------- in this macro invocation
   |
   = note: available fields are: `sin_family`, `sin_port`, `sin_addr`, `sin_zero`

error[E0308]: mismatched types
  --> src/macros/mod.rs:8:25
   |
8  |             sin_family: libc::AF_INET as u8,
   |                         ^^^^^^^^^^^^^^^^^^^ expected u16, found u8
   |
  ::: src/client.rs:19:24
   |
19 |         let servaddr = sockaddr!([127, 0, 0, 1], 8000);
   |                        ------------------------------- in this macro invocation

error[E0308]: mismatched types
  --> src/macros/mod.rs:13:24
   |
13 |             sin_zero: [0i8; 8],
   |                        ^^^ expected u8, found i8
   |
  ::: src/client.rs:19:24
   |
19 |         let servaddr = sockaddr!([127, 0, 0, 1], 8000);
   |                        ------------------------------- in this macro invocation
   |
help: change the type of the numeric literal from `i8` to `u8`
   |
13 |             sin_zero: [0u8; 8],
   |                        ^^^

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0308, E0560.
For more information about an error, try `rustc --explain E0308`.
error[E0308]: mismatched types
  --> src/macros/mod.rs:8:25
   |
8  |             sin_family: libc::AF_INET as u8,
   |                         ^^^^^^^^^^^^^^^^^^^ expected u16, found u8
   |
  ::: src/server.rs:69:24
   |
69 |         let servaddr = sockaddr!([127, 0, 0, 1], 8000);
   |                        ------------------------------- in this macro invocation

error[E0308]: mismatched types
  --> src/macros/mod.rs:13:24
   |
13 |             sin_zero: [0i8; 8],
   |                        ^^^ expected u8, found i8
   |
  ::: src/server.rs:69:24
   |
69 |         let servaddr = sockaddr!([127, 0, 0, 1], 8000);
   |                        ------------------------------- in this macro invocation
   |
help: change the type of the numeric literal from `i8` to `u8`
   |
13 |             sin_zero: [0u8; 8],
   |                        ^^^

error: could not compile `rshell`.
warning: build failed, waiting for other jobs to finish...
error: aborting due to 3 previous errors

Some errors have detailed explanations: E0308, E0560.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `rshell`.

**Comment by zhenyuanlau** [comment]
Thank you for the issue. I try to fix it in commit https://github.com/zhenyuanlau/rshell/commit/6e4569b9f99829a033645bbe4be7dd84cc0af149.   I'm a novice at rust programming. I use another api to make implementation more simple. I keep the macro code because I am learning the features of Rust. I use **#[cfg]** to compile **sin_len** according different target os. Also, I am poor in English. I hope you can understand what I expressed. @skydig
